### PR TITLE
Common patterns `navigator+tabbar` and `splitter+navigator`

### PR DESCRIPTION
**Pull request by misterjunio**
@frandiox here is a PR with two of the main navigation patterns we have in all bindings. I was able to make splitter work with navigator in React as well.

The only issue is that case in Vue: loading a page selected from the menu by simply resetting the navigator's page-stack to that page causes a push animation when I want fade 😕  I don't see a way of managing this through the props, I could change the navigator's animation but that would affect the 'regular' pushes as well.

I could also maybe try to have the navigator outside of the splitter instead (as in your kitchensink) and have the animation option as a prop but that would change the design of the example from all the other bindings so I didn't want to do that.. if you see any other option feel free to change it or let me know, otherwise I guess it's fine to keep it like this.

### CODE REVIEW

**Comment by frandiox** [comment]
@misterjunio Thanks, looks great!

About the Vue issue, yes, the only way right now is changing the `options` prop and then change it back (like [here](https://github.com/frandiox/vue-onsenui-kitchensink/blob/no-vuex/src/pages/Animations.vue#L2)).

Perhaps we can do the following:

```javascript
pageStack.push({ extends: myPage, navigatorOptions: { animation: ..., ... } });
```

Although that would only work for pushing pages, not for popping. Another solution would be providing extra methods in the pageStack... something like `pageStack.pushPage` and `pageStack.popPage`. But that would add some complexity...

**Comment by frandiox** [comment]
@misterjunio One thing, Vue's "Navigator Outside Tabbar" shows some erros in console. The third tab has 2 toolbars, gets an 'openMenu' prop but there is no menu, and has some `<ons-` elements (instead of `<v-ons-`. Also, the second tab doesn't push new pages with cards at least using my local version. Could you double check?

**Comment by misterjunio** [comment]
@frandiox those last errors were a confusion with the other tutorials, too many of them 😅  hopefully everything is fixed now

I managed to introduce the fade in the splitter, in this case it turned out that switching between the animations was even simpler, just set the option before pushing and unset on `postpush` event. I agree that it is not good to be adding methods in Vue so I guess this is good enough 👍

**Comment by frandiox** [comment]
@misterjunio I think this doesn't need to be updated for 2.4.0 so I will merge it now. Thanks a lot!

**Pull request merged**
