### PR TITLE
Created common use passing data to and from elements

### PR DESCRIPTION
**Pull request by munsterlander**

### CODE REVIEW

**Comment by munsterlander** [comment]
Hopefully the explanation is in the format you want.  Let me know if you want something changed.

**Comment by frankdiox** [comment]
@munsterlander Thanks for the PR! I will review this soon. It's also necessary to modify `modules.js` to add this file to the dictionary since we don't have a server :smile: 
I'll do that, don't worry!

**Comment by munsterlander** [comment]
@frankdiox I did not know about that file, but I do now!  In the future, I can modify as well.

**Comment by frankdiox** [comment]
@munsterlander [Here it is](http://tutorial.onsen.io/?framework=vanilla&category=Community%20tutorials&module=passing_data) :)

I named it `Passing data outside Onsen UI` because at least for `ons-navigator` there is actually a way to pass data within the framework itself, with the `data` object. Also I did some minor changes to the code.

For the next time, you can just clone this repo and serve it. It's completely standalone so you can test the result in local.

**Comment by munsterlander** [comment]
Sweet!  I came close to throwing in passing data in the options block but I thought the reference docs did  a pretty good job explaining that and I was afraid to make it too big.  It could be added if you think it is necessary though or my method is a poor way of doing it.  I know in the forums we have talked about globals, outside passing, and other pros / cons of this way.

**Pull request closed without merging**
