### PR TITLE
Created common use passing data to and from elements

### PR DESCRIPTION
**Pull request by munsterlander**
I probably need to go back and add explanation of the code the way the other use case does.  Just didn't have much time and wanted to jot this down because this is probably the number one thing I answer in the forums and SO.

### CODE REVIEW

**Comment by argelius** [comment]
Thanks a lot @munsterlander ! Looks great :)

We will add this when you've added the explanation or one of us could do it if you are short on time.

**Comment by argelius** [comment]
@munsterlander I meant to write a comment but accidentally merged :)

**Comment by munsterlander** [comment]
Ha!  No prob.  I will probably get an explanation in later today.  I im'd Fran regarding a good gui tool for github markdown.  Do you know of one?

**Comment by argelius** [comment]
@munsterlander I only know of online editors. I've used [Dillinger](http://dillinger.io/) before and it's pretty nice.

**Comment by munsterlander** [comment]
So in order to edit this file and to recommit, do I need to revert the PR, because at this time, the file is locked where I can't fork/edit?  Also, I stumbled on this editor and it is pretty slick: https://stackedit.io/editor

**Comment by argelius** [comment]
@munsterlander I've already reverted this PR so you can make a new PR with the same changes.

**Comment by munsterlander** [comment]
I have it now.  I didn't realize that I hadn't forked the tutorial branch and I wasn't able to find my file.  Woops!  Fixed now.  I am finishing up the explanation now and will be dropping a PR shortly.

**Pull request merged**
